import type { Intake } from "./types";

/** Demo intake only — never used as engine defaults. Generic week, not a real client. */
export const SAMPLE_INTAKE: Intake = {
  name: "Alex Rivera",
  email: "alex@example.com",
  age: 36,
  sex: "M",
  height: "5'11\"",
  weight: 198,
  goal_weight: 185,
  start_date: "2026-09-07",
  sleep_hours: 7,
  job_type: "desk",
  month_intent: "cut",
  goal: "Drop the winter layer without losing the lifts",
  experience: "intermediate",
  hurts: "knees get cranky on lunges",
  eq_barbell: true,
  eq_db: true,
  eq_cable: true,
  eq_machines: true,
  eq_bands: true,
  eq_body: true,
  place_gym: true,
  place_home: true,
  place_outdoor: true,
  place_track: false,
  lean_both: true,
  lean_strength: false,
  lean_cardio: false,
  calorie_choice: "keep",
  calorie_custom: "",
  meals_per_day: 3,
  meal_times: "morning, afternoon, night",
  activity_level: "light",
  day_mon_sc: "S",
  day_mon_detail: "Full body",
  day_mon_when: "Evening",
  day_mon_min: 45,
  day_tue_sc: "C",
  day_tue_detail: "Swim",
  day_tue_when: "Evening",
  day_tue_min: 45,
  day_wed_sc: "S",
  day_wed_detail: "Upper",
  day_wed_when: "Evening",
  day_wed_min: 45,
  day_wed_sc2: "C",
  day_wed_detail2: "Walk",
  day_wed_when2: "Morning",
  day_wed_min2: 30,
  day_thu_sc: "R",
  day_thu_detail: "Off",
  day_thu_when: "Evening",
  day_thu_min: 45,
  day_fri_sc: "S",
  day_fri_detail: "Lower",
  day_fri_when: "Evening",
  day_fri_min: 45,
  day_sat_sc: "C",
  day_sat_detail: "Run",
  day_sat_when: "Morning",
  day_sat_min: 45,
  day_sun_sc: "R",
  day_sun_detail: "Off",
  day_sun_when: "Evening",
  day_sun_min: 45,
  prot_chicken: true,
  prot_steak: true,
  prot_eggs: true,
  prot_fish: true,
  prot_shrimp: true,
  prot_veg: false,
  starch_rice: true,
  starch_potato: true,
  starch_oats: true,
  starch_pasta: true,
  starch_bread: true,
  veg_greens: true,
  veg_broccoli: true,
  veg_beans: true,
  veg_mixed: true,
  cook_mode: "home",
  mug_oz: 32,
  dairy_whey: "yes",
  allergies: "None",
  restrictions: "None",
  likes: "eggs, rice bowls, salmon",
  adjust_stack: true,
  no_supps: false,
  supp1_type: "multi",
  supp1_form: "pill",
  supp1_dose: "1 daily",
  supp2_type: "creatine",
  supp2_form: "powder",
  supp2_dose: "5 g",
  medications: "None",
  fast_yes: true,
  fast_length: "36",
  fast_count: 2,
  fast_never: "Saturday, race day",
  fast_history: "Done a 24 before. First 36 this month.",
  run_yes: true,
  run_now: "2 miles easy",
  run_goal: "5K",
  run_race: "local 5K in October",
  swim_access: true,
  swim_where: "indoor pool",
  swim_program: "yes",
  sport_hockey: false,
  sport_boxing: false,
  sport_basketball: false,
  sport_soccer: false,
  sport_tennis: false,
  sport_golf: false,
  sport_other: "",
  blocked_dates: "2026-09-26",
  blocked_why: "travel",
  blocked_plan: "walk only",
  blocked_food: "airport protein + rice",
};

export function emptyIntake(): Intake {
  const start = new Date();
  const iso = `${start.getFullYear()}-${String(start.getMonth() + 1).padStart(2, "0")}-${String(start.getDate()).padStart(2, "0")}`;
  return {
    name: "",
    email: "",
    age: "",
    sex: "M",
    height: "",
    weight: "",
    goal_weight: "",
    start_date: iso,
    sleep_hours: 7,
    job_type: "desk",
    month_intent: "cut",
    goal: "",
    experience: "intermediate",
    hurts: "",
    meals_per_day: 3,
    meal_times: "",
    mug_oz: 32,
    dairy_whey: "yes",
    cook_mode: "home",
    calorie_choice: "keep",
    calorie_custom: "",
    adjust_stack: true,
    day_mon_sc: "R",
    day_mon_detail: "Off",
    day_mon_when: "Evening",
    day_mon_min: 45,
    day_tue_sc: "R",
    day_tue_detail: "Off",
    day_tue_when: "Evening",
    day_tue_min: 45,
    day_wed_sc: "R",
    day_wed_detail: "Off",
    day_wed_when: "Evening",
    day_wed_min: 45,
    day_thu_sc: "R",
    day_thu_detail: "Off",
    day_thu_when: "Evening",
    day_thu_min: 45,
    day_fri_sc: "R",
    day_fri_detail: "Off",
    day_fri_when: "Evening",
    day_fri_min: 45,
    day_sat_sc: "R",
    day_sat_detail: "Off",
    day_sat_when: "Evening",
    day_sat_min: 45,
    day_sun_sc: "R",
    day_sun_detail: "Off",
    day_sun_when: "Evening",
    day_sun_min: 45,
    prot_chicken: false,
    prot_steak: false,
    prot_eggs: false,
    prot_fish: false,
    prot_shrimp: false,
    prot_veg: false,
    starch_rice: false,
    starch_potato: false,
    starch_oats: false,
    starch_pasta: false,
    starch_bread: false,
    veg_greens: false,
    veg_broccoli: false,
    veg_beans: false,
    veg_mixed: false,
    eq_barbell: false,
    eq_db: false,
    eq_cable: false,
    eq_machines: false,
    eq_bands: false,
    eq_body: false,
    place_gym: false,
    place_home: false,
    place_outdoor: false,
    place_track: false,
    lean_strength: false,
    lean_cardio: false,
    lean_both: false,
    run_yes: false,
    run_now: "",
    run_goal: "",
    run_race: "",
    swim_access: false,
    swim_where: "",
    sport_hockey: false,
    sport_boxing: false,
    sport_basketball: false,
    sport_soccer: false,
    sport_tennis: false,
    sport_golf: false,
    sport_other: "",
    blocked_food: "",
  };
}
