export const DAY_KEYS = ["mon", "tue", "wed", "thu", "fri", "sat", "sun"] as const;
export type DayKey = (typeof DAY_KEYS)[number];
export const DAY_LABELS = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"] as const;
export type Kind = "S" | "C" | "R";
export type When = "Morning" | "Afternoon" | "Evening";
export type Intent = "maintain" | "cut" | "push";

export type Intake = {
  name?: string;
  email?: string;
  age?: string | number;
  sex?: string;
  height?: string | number;
  weight?: string | number;
  weight_lb?: string | number;
  goal_weight?: string | number;
  start_date?: string;
  sleep_hours?: string | number;
  job_type?: string;
  month_intent?: string;
  goal?: string;
  activity_level?: string;
  activity?: string;
  experience?: string;
  hurts?: string;
  eq_barbell?: unknown;
  eq_db?: unknown;
  eq_cable?: unknown;
  eq_machines?: unknown;
  eq_bands?: unknown;
  eq_body?: unknown;
  place_gym?: unknown;
  place_home?: unknown;
  place_outdoor?: unknown;
  place_track?: unknown;
  sport_hockey?: unknown;
  sport_boxing?: unknown;
  sport_basketball?: unknown;
  sport_soccer?: unknown;
  sport_tennis?: unknown;
  sport_golf?: unknown;
  sport_other?: string;
  lean_strength?: unknown;
  lean_cardio?: unknown;
  lean_both?: unknown;
  lean?: string;
  run_yes?: unknown;
  run_now?: string;
  run_goal?: string;
  run_race?: string;
  run_priority?: unknown;
  swim_access?: unknown;
  swim_where?: string;
  swim_program?: unknown;
  blocked_dates?: string;
  blocked_why?: string;
  blocked_plan?: string;
  blocked_food?: string;
  meals_per_day?: string | number;
  meals?: string | number;
  meal_times?: string;
  prot_chicken?: unknown;
  prot_steak?: unknown;
  prot_turkey?: unknown;
  prot_pork?: unknown;
  prot_fish?: unknown;
  prot_shrimp?: unknown;
  prot_eggs?: unknown;
  prot_veg?: unknown;
  starch_rice?: unknown;
  starch_potato?: unknown;
  starch_pasta?: unknown;
  starch_bread?: unknown;
  starch_oats?: unknown;
  veg_greens?: unknown;
  veg_broccoli?: unknown;
  veg_beans?: unknown;
  veg_mixed?: unknown;
  cook_mode?: string;
  mug_oz?: string | number;
  mug?: string | number;
  likes?: string;
  allergies?: string;
  dairy_whey?: string;
  restrictions?: string;
  no_supps?: unknown;
  adjust_supps?: unknown;
  adjust_stack?: unknown;
  meds?: string;
  medications?: string;
  supp1_type?: string;
  supp1_form?: string;
  supp1_dose?: string;
  supp2_type?: string;
  supp2_form?: string;
  supp2_dose?: string;
  supp3_type?: string;
  supp3_form?: string;
  supp3_dose?: string;
  supp4_type?: string;
  supp4_form?: string;
  supp4_dose?: string;
  listed?: { type?: string; name?: string; form?: string; dose?: string }[];
  fast_yes?: unknown;
  fast_history?: string;
  fast_never?: string;
  fast_length?: string;
  fast_hours?: string | number;
  fast_count?: string | number;
  fast_when?: string;
  notes?: string;
  calorie_choice?: string;
  calorie_custom?: string | number;
  calories?: string | number;
  session_min?: string | number;
  week?: Record<string, unknown>;
  [key: string]: unknown;
};

export type VitItem = {
  name: string;
  dose: string;
  when: string;
  why: string;
  status: "KEEP" | "ADD" | "OPTIONAL" | "SKIP";
};

export type VitPlanDict = {
  band: string;
  sex: string;
  has_multi: boolean;
  keep: VitItem[];
  add: VitItem[];
  optional: VitItem[];
  notes: string[];
  page_lines: [string, string, string, string][];
  why_we_changed: string;
  changes: { action: string; name: string; why: string }[];
  rda_highlights: Record<string, number>;
};

export type DayPlan = {
  dow: number;
  key: DayKey;
  label: string;
  kind: Kind;
  type: string;
  when: When;
  minutes: number;
};

export type WorkSet = {
  move: string;
  sets: number;
  reps: string;
  cue: string;
  how: string;
  slug: string;
  url: string;
};

export type Session = DayPlan & {
  title: string;
  work: WorkSet[];
  note: string;
  met?: number;
  gross?: number;
  net?: number;
};

export type Plate = {
  title: string;
  items: string[];
  protein_g: number;
  kcal: number | null;
  starch_cups: number | null | undefined;
  facts: string;
  line: string;
};

export type Slot = {
  name: string;
  protein_g: number;
  meat_oz: number | null;
  kcal: number | null;
  fat_g: number | null;
  carb_g: number | null;
  starch: boolean;
  starch_cups: number | null;
};

export type Playbook = {
  brand: {
    name: string;
    tagline: string;
    disclaimer: string;
    colors: Record<string, string>;
  };
  chapters: [string, string, string][];
  sources: [string, string, string[]][];
  who: {
    name?: string;
    email?: string;
    age: number | null;
    sex: string;
    height?: string | number;
    weight: number;
    goal_weight: number | null;
    start_date?: string;
    sleep_hours?: string | number;
    job_type?: string;
    month_intent?: string;
    goal?: string;
  };
  numbers: {
    kg?: number;
    protein_g?: [number, number];
    protein_mid?: number;
    protein_meals?: number[];
    water_oz_rest?: number;
    water_oz_train?: number;
    water_fills?: [string, string];
    cut_lb_30d?: [number, number];
    sitting_g?: [number, number];
    strength_days_min?: number;
    sets_per_exercise?: [number, number];
  };
  water: Record<string, unknown>;
  calories: Record<string, unknown> & {
    daily?: number | null;
    recommended?: number | null;
    rest_day?: number | null;
    train_day_kcal?: number | null;
    bmr?: number | null;
    note?: string;
    day_targets?: {
      label?: string;
      kind?: string;
      type?: string;
      met?: number;
      minutes?: number;
      net_kcal?: number;
      eatback_kcal?: number;
      daily_kcal?: number | null;
    }[];
    burn?: {
      days: Session[];
      weekly_net: number;
      weekly_gross: number;
      daily_avg_net: number;
      formula: string;
      source: string;
    };
    choice?: string;
    custom?: number | null;
    floor?: number;
    floored?: boolean;
    eatback?: number;
    train_add?: number;
    deficit?: number;
    surplus?: number;
    planned_lb_30d?: number;
    wanted_lb_30d?: number;
    maintain?: number | null;
    occupational?: number | null;
    activity?: string;
    activity_factor?: number;
  };
  food: {
    meals_per_day: number;
    slots: Slot[];
    proteins: string[];
    starches: string[];
    vegs: string[];
    breakfasts: string[];
    snacks: string[];
    cook_mode: string;
    plate_style: string;
    vegetarian: boolean;
    dairy_ok: boolean;
    likes: string;
    allergies: string;
    restrictions: string;
    daily_kcal: number | null;
    macros: {
      daily_kcal: number;
      protein_g: number;
      protein_kcal: number;
      fat_g: number;
      fat_kcal: number;
      carb_g: number;
      carb_kcal: number;
      tight: boolean;
    } | null;
    calorie_choice?: string;
    fiber_g: number | null;
    rest_day_kcal?: number | null;
    train_day_kcal?: number | null;
    eggs: {
      eggs: number;
      from_eggs: number;
      leftover_g: number;
      leftover_oz: number;
      whey_scoops: number;
      line: string;
    };
    menu: {
      breakfast: Plate[];
      lunch: Plate[];
      dinner: Plate[];
      eggs: Record<string, unknown>;
      starch_cups_day: number;
      veg_cups_day: number;
      budget: string;
      variety: string;
      source: string;
    };
    rule: string;
    citation: string;
    source: string;
  };
  exercise: {
    intent: string;
    experience: string;
    equipment: string[];
    hurts: string;
    sessions: Session[];
    volume: [number, number];
    moves_url: string;
    interactive: boolean;
    rule: string;
    tap_banner: string;
    tap_chip: string;
    tap_hint: string;
    run_guide?: {
      on: boolean;
      distance: string;
      label: string;
      goal: string;
      now?: string | null;
      race?: string | null;
      level: string;
      days_per_week: number;
      start_miles: number;
      weeks: {
        week: number;
        miles: number;
        easy: string;
        quality: string;
        long: string;
        fourth?: string | null;
      }[];
      rules: string[];
      source: string;
    } | null;
  };
  week: {
    days: DayPlan[];
    strength_days: number;
    cardio_days: number;
    sport_days: string[];
    note: string;
  };
  stack: VitPlanDict;
  why_we_changed: string;
  vitamin_changes: { action: string; name: string; why: string }[];
  fasting: {
    wanted: boolean;
    days: string[];
    windows: {
      empty: string;
      core: string[];
      start_evening: string;
      break_morning: string;
      hours: number;
      why: string;
    }[];
    auto_placed: boolean;
    tips: string[];
    key: [string, string][];
    rule: string;
    length?: string;
    hours?: number;
    count?: number;
    never?: string;
    when?: string;
    history?: string;
    new?: boolean;
  };
  blocked: {
    dates: string;
    why: string;
    plan: string;
    food: string;
    rule: string;
  };
  chrome: Record<string, string>;
  tools: Record<string, unknown>;
  sport_fuel: { label?: string; type: string; when?: string; note: string }[];
  calendar: Record<string, string> | null;
  honest_cut: boolean;
  opening_note: string;
  assumptions: string[];
  guide: {
    session: string[];
    sport: string[];
    food: string[];
    miss: string[];
    stack: string[];
    fast: string[];
    windows: unknown[];
    rule: string;
  };
  rda: Record<string, number>;
  margins: Record<string, unknown>;
  logic: Record<string, string>;
  audit: string[];
  review: {
    ok: boolean;
    ready: boolean;
    errors: string[];
    warnings: string[];
    checks: string[];
    summary: string;
  };
};
