/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as MealRouteImport } from './routes/meal'
import { Route as MovesRouteImport } from './routes/moves'
import { Route as PlaybookRouteImport } from './routes/playbook'
import { Route as VitaminsRouteImport } from './routes/vitamins'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const MealRoute = MealRouteImport.update({
  id: '/meal',
  path: '/meal',
  getParentRoute: () => rootRouteImport,
} as any)
const MovesRoute = MovesRouteImport.update({
  id: '/moves',
  path: '/moves',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookRoute = PlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => rootRouteImport,
} as any)
const VitaminsRoute = VitaminsRouteImport.update({
  id: '/vitamins',
  path: '/vitamins',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/intake': typeof IntakeRoute
  '/meal': typeof MealRoute
  '/moves': typeof MovesRoute
  '/playbook': typeof PlaybookRoute
  '/vitamins': typeof VitaminsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/intake': typeof IntakeRoute
  '/meal': typeof MealRoute
  '/moves': typeof MovesRoute
  '/playbook': typeof PlaybookRoute
  '/vitamins': typeof VitaminsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/intake': typeof IntakeRoute
  '/meal': typeof MealRoute
  '/moves': typeof MovesRoute
  '/playbook': typeof PlaybookRoute
  '/vitamins': typeof VitaminsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/intake' | '/meal' | '/moves' | '/playbook' | '/vitamins'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/intake' | '/meal' | '/moves' | '/playbook' | '/vitamins'
  id:
    | '__root__'
    | '/'
    | '/intake'
    | '/meal'
    | '/moves'
    | '/playbook'
    | '/vitamins'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IntakeRoute: typeof IntakeRoute
  MealRoute: typeof MealRoute
  MovesRoute: typeof MovesRoute
  PlaybookRoute: typeof PlaybookRoute
  VitaminsRoute: typeof VitaminsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal': {
      id: '/meal'
      path: '/meal'
      fullPath: '/meal'
      preLoaderRoute: typeof MealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moves': {
      id: '/moves'
      path: '/moves'
      fullPath: '/moves'
      preLoaderRoute: typeof MovesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook': {
      id: '/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof PlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vitamins': {
      id: '/vitamins'
      path: '/vitamins'
      fullPath: '/vitamins'
      preLoaderRoute: typeof VitaminsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IntakeRoute: IntakeRoute,
  MealRoute: MealRoute,
  MovesRoute: MovesRoute,
  PlaybookRoute: PlaybookRoute,
  VitaminsRoute: VitaminsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
